### PR TITLE
Test with targetSdk 34

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by buiduclam09** [comment]
I think startForground: 
image

**Comment by yschimke** [comment]
Thanks, this agrees https://medium.com/@domen.lanisnik/guide-to-foreground-services-on-android-9d0127dc8f9a

**Comment by yschimke** [comment]
@buiduclam09 Thanks, updated

**Comment by breanatate** [comment]
Did some more testing -- even with the most recent bump to 34 and these changes, the exception will appear if the screen is off when the app launches.

I wasn't observing this with the emulator because the emulator is (normally) awake while the app launches. If you palm the emulator or start with screen off on a physical device, the issue persists.

**Pull request closed without merging**
